### ISSUE TITLE
Ensure all utils have updated npm ignore, docs branch and building, etc based on the updated util template (except dapi-types since it doesn't need tests/docs)

### ISSUE THREAD

**Issue by bdistin** [dirigeants/Project-Blue#13]

**Comment by kyranet** [comment]
Linked to:

- **async-queue**: https://github.com/dirigeants/async-queue/pull/67
- **bitfield**: https://github.com/dirigeants/bitfield/pull/55
- **cache**: https://github.com/dirigeants/cache/pull/67
- **cron**: https://github.com/dirigeants/cron/pull/146
- **stopwatch**: https://github.com/dirigeants/stopwatch/pull/120
- **timestamp**: https://github.com/dirigeants/timestamp/pull/166
- **type**: https://github.com/dirigeants/type/pull/179
- **utils**: https://github.com/dirigeants/utils/pull/168
- **ws**: https://github.com/dirigeants/ws/pull/79
