### ISSUE TITLE
[RFC] Rename repository to reflect future package name

### ISSUE THREAD

**Issue by Favna** [dirigeants/Project-Blue#183]
# Summary

On various days in the past weeks we have been discussing the definitive name that Project Blue will have once we publish the first stable release to NPM. After some discussion, and if I may so humble, my own suggestion of a set of `@dirigeants/core` (Project Blue), `@dirigeants/framework` (Project Red) and `@dirigeants/voice` (Project Green) it seemed like the suggestion was appealing to many. These names are however not yet seen on GitHub and this should change before we publish our API library to NPM.

# Motivation

First of all, a repository name that doesn't also reflect the name of the package that it is publishing can be extremely confusing, for example take various packages that have `node-<something>` as their repository name, but only `<something>` as their package name.

Secondly, giving this repository a proper name will give it a much more professional look and represent its state of getting every closer to a first official release.

And lastly giving this repository a proper name is also a first step to properly describing it in a README, something that's a must have before we can publish the package and which should always start with the name of the package in some way or another, ergo that information has to be locked in.

# Detailed design

Assuming the names as was suggested before and reiterated in the summary then there are various reasons to go with these names
- They fully reflect this GitHub organization, the name of the GitHub organization is Dirigeants and so the packages should be scoped under Dirigeants
- The names of `core`, `framework` and `voice` do not need whole essays\* to explain them. They're concise, to the point, easy to type and easy to remember.
- To my knowledge this would make us the first development team to make proper use of GitHub organizations as well as NPM organizations, if anything from the very start (i.e. DiscordJS moved to a GitHub organization only much later in its lifetime). This grants us a great distinction from other API libraries for Discord and distinction is something we will very much need in a landscape where there are many different API libraries and frameworks to use for developing Discord bots.
- All other related repositories, such as [dirigeants/ws](https://github.com/dirigeants/ws), should have their descriptions updated to reflect the new name.

# Drawbacks

When we rename this repository it is only fitting that in chat we will also start referring to this project by its official name, for example "diricore". This will take some getting used to.

# Alternatives

It has been considered that rather than publishing under the `@dirigeants` scope that we would publish these packages under the `@klasa` scope to NPM. This however loops back to what I said about repository name reflecting the package name and vice versa. If we publish the packages as `@klasa/core` then it would make sense to either rename this GitHub organization to `klasa` (and rename all the old `klasa` related repositories as well to avoid unnecessary confusion). As @kyranet has managed to get ownership rights in the `@dirigeants` scope on NPM however it should no longer be an issue to use the `@dirigeants` scope.

# Unresolved questions

- Will we republish packages such as [dirigeants/ws](https://github.com/dirigeants/ws) as `@dirigeants/ws` and use `npm deprecate` on the current packages?
  - Subquestion: Will we do this along with the first release of `@dirigeants/core` and if so, will the these packages get auto-bumped to v1.0.0 in order to match the version number of `@dirigeants/core`?
  - Alternatively if the packages are not republished under the proper scope, will they still get auto-bumped to v1.0.0?
- Which repositories on this GitHub org are actually relevant for the `@dirigeants/core`? This should be documented somewhere. Ideally that place would be either through wikipages on this repository (being the "main" repository) or on a repository simply called `docs` where we will put all documentation that is not directly API documentation.

\* 108 words for Klasa, but leave it to Kyra to come up with a more convoluted lore than solving Goldbach's Conjecture

**Comment by cfanoulis** [comment]
+1 on this, even though I would *seriously* prefer a non-scoped package name, since it shows that the library may only be used in conjunction with klasa.

**Comment by bdistin** [comment]
Nothing will be under @dirigeants/ There won't be a @klasa/framework , that will remain just klasa.

**Comment by tjrgg** [comment]
If the framework isn't going to be scoped, then this library probably shouldn't be scoped either, imo. Since klasa would depend on this library, it doesn't make logical sense to me to put this library under the klasa scope, as that implies the opposite, no?
